### ISSUE TITLE
Doesn't work on Fedora 41

### ISSUE THREAD

**Issue by BruceWayne-Linux** [FrancescoCaracciolo/material-you-colors#8]
Hi. First of all, thanks a lot for reviving this extension. It's really a huge plus for customizing gnome.

I'm on Fedora 41, upgraded from beta to stable yesterday.
I came to know about the extension day before yesterday and installed it that day. The colors were not applying properly but if i check with pywal(from terminal) the color schemes are correct, but the extension is not picking it on fedora.
Yesterday, I installed the same extension and tried it on arch(endeavouros). It worked flawlessly.
Here are some screenshots of the coloring in fedora and arch for the same wallpapers:
![Screenshot From 2024-10-31 06-46-16](https://github.com/user-attachments/assets/ad212072-a546-4a0a-88eb-dd0957e8b942)
![Screenshot From 2024-10-31 07-00-03](https://github.com/user-attachments/assets/b0a3ff27-573c-4eca-a3b5-3c89c2032fce)

![Screenshot From 2024-10-31 06-47-05](https://github.com/user-attachments/assets/1415a213-743e-41f0-a785-4d859cbd08de)
![Screenshot From 2024-10-31 07-01-06](https://github.com/user-attachments/assets/f6bcfafc-7391-45d0-8898-94f3944112f1)

![Screenshot From 2024-10-31 06-49-41](https://github.com/user-attachments/assets/f0495155-1eb1-4ba2-abe2-7f57a765aa7a)
![Screenshot From 2024-10-31 07-02-04](https://github.com/user-attachments/assets/c8da99ce-43e7-4239-82a9-f0e11ed8d483)

![Screenshot From 2024-10-31 06-51-47](https://github.com/user-attachments/assets/22349497-7987-470a-8be3-ef878d0d4b89)
![Screenshot From 2024-10-31 07-02-49](https://github.com/user-attachments/assets/701b0854-8b23-44f5-ab1d-a59ff15276d5)

**Comment by BruceWayne-Linux** [comment]
I think this issue is not specific to just Fedora 41 but rather Fedora in general.
I came across this issue while i was looking for a fix: https://github.com/avanisubbiah/material-you-theme/issues/71
Could be related.

**Comment by FrancescoCaracciolo** [comment]
Have you tried using the python backend in Fedora?

**Comment by BruceWayne-Linux** [comment]
yea, but that totally removes the material you colors and gives the default gnome theme.
![Screenshot From 2024-10-31 10-21-15](https://github.com/user-attachments/assets/1fab4382-c55c-4f2f-91cd-3cc9e10827df)

**Comment by FrancescoCaracciolo** [comment]
Try installing the sass package on Fedora and running the python backend

**Comment by FrancescoCaracciolo** [comment]
Also, if you still have issue with python backend, go into
`~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-materialu`, run `./run_integration.sh` and send the output here

**Comment by BruceWayne-Linux** [comment]
> Try installing the sass package on Fedora and running the python backend

Okay. Installed sass from npm and also R-sass(from fedora offical repositories).
Didn't work. still it's using default gnome theme.

**Comment by BruceWayne-Linux** [comment]
> Also, if you still have issue with python backend, go into `~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-materialu`, run `./run_integration.sh` and send the output here

It's giving a error.
![Screenshot From 2024-10-31 17-19-32](https://github.com/user-attachments/assets/fe488b31-dce8-4839-bd73-403fc4709bfc)

**Comment by BruceWayne-Linux** [comment]
Also, while i was turning off and on the extension after logout, this error came.
It's not happening always but came 2 or 3 time now.
Could this be a cause for the malfunction of the extension?
![Screenshot From 2024-10-31 10-50-49](https://github.com/user-attachments/assets/2a3d6730-b235-474a-9686-6246b27d591e)
(turned off the python backend here)

**Comment by FrancescoCaracciolo** [comment]
> > Also, if you still have issue with python backend, go into `~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-materialu`, run `./run_integration.sh` and send the output here
> 
> It's giving a error. ![Screenshot From 2024-10-31 17-19-32](https://private-user-images.githubusercontent.com/87817029/381936921-fe488b31-dce8-4839-bd73-403fc4709bfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzc5NDMsIm5iZiI6MTczMDM3NzY0MywicGF0aCI6Ii84NzgxNzAyOS8zODE5MzY5MjEtZmU0ODhiMzEtZGNlOC00ODM5LWJkNzMtNDAzZmM0NzA5YmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEyMjcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NWYxOTJhNWUwZDFjYzFkZTBmMjJiYmMyOWRmMTc1YmMxMTYzNjMwMmE0NWY3Y2E3MGQ1MTNhZmZmNzdkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dWp56dccWvbE-fnwSa1nWBF5Cq7Z7hFhxL4LNjwKpvs)

For now let's solve this issue.
Try running ./local-install.sh in the same folder and then try running that command again

**Comment by BruceWayne-Linux** [comment]
Getting an error.

```

Collecting rich (from -r requirements.txt (line 1))
  Using cached rich-13.9.3-py3-none-any.whl.metadata (18 kB)
Collecting pillow (from -r requirements.txt (line 2))
  Using cached pillow-11.0.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pygobject (from -r requirements.txt (line 3))
  Using cached pygobject-3.50.0.tar.gz (1.1 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      Collecting meson-python>=0.12.1
        Using cached meson_python-0.17.1-py3-none-any.whl.metadata (4.1 kB)
      Collecting pycairo>=1.16
        Using cached pycairo-1.27.0.tar.gz (661 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [48 lines of output]
            + meson setup /tmp/pip-install-tw8dj5cn/pycairo_03c0def5edfc40ee9d4235b213c4a82f /tmp/pip-install-tw8dj5cn/pycairo_03c0def5edfc40ee9d4235b213c4a82f/.mesonpy-243nssi0 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dwheel=true -Dtests=false --native-file=/tmp/pip-install-tw8dj5cn/pycairo_03c0def5edfc40ee9d4235b213c4a82f/.mesonpy-243nssi0/meson-python-native-file.ini
            The Meson build system
            Version: 1.6.0
            Source dir: /tmp/pip-install-tw8dj5cn/pycairo_03c0def5edfc40ee9d4235b213c4a82f
            Build dir: /tmp/pip-install-tw8dj5cn/pycairo_03c0def5edfc40ee9d4235b213c4a82f/.mesonpy-243nssi0
            Build type: native build
            Project name: pycairo
            Project version: 1.27.0
            C compiler for the host machine: cc (gcc 14.2.1 "cc (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3)")
            C linker for the host machine: cc ld.bfd 2.43.1-2
            Host machine cpu family: x86_64
            Host machine cpu: x86_64
            Program python3 found: YES (/home/peter/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-material-you/venv/bin/python3)
            Compiler for C supports arguments -Wall: YES
            Compiler for C supports arguments -Warray-bounds: YES
            Compiler for C supports arguments -Wcast-align: YES
            Compiler for C supports arguments -Wconversion: YES
            Compiler for C supports arguments -Wextra: YES
            Compiler for C supports arguments -Wformat=2: YES
            Compiler for C supports arguments -Wformat-nonliteral: YES
            Compiler for C supports arguments -Wformat-security: YES
            Compiler for C supports arguments -Wimplicit-function-declaration: YES
            Compiler for C supports arguments -Winit-self: YES
            Compiler for C supports arguments -Winline: YES
            Compiler for C supports arguments -Wmissing-format-attribute: YES
            Compiler for C supports arguments -Wmissing-noreturn: YES
            Compiler for C supports arguments -Wnested-externs: YES
            Compiler for C supports arguments -Wold-style-definition: YES
            Compiler for C supports arguments -Wpacked: YES
            Compiler for C supports arguments -Wpointer-arith: YES
            Compiler for C supports arguments -Wreturn-type: YES
            Compiler for C supports arguments -Wshadow: YES
            Compiler for C supports arguments -Wsign-compare: YES
            Compiler for C supports arguments -Wstrict-aliasing: YES
            Compiler for C supports arguments -Wundef: YES
            Compiler for C supports arguments -Wunused-but-set-variable: YES
            Compiler for C supports arguments -Wswitch-default: YES
            Compiler for C supports arguments -Wno-missing-field-initializers: YES
            Compiler for C supports arguments -Wno-unused-parameter: YES
            Compiler for C supports arguments -fno-strict-aliasing: YES
            Compiler for C supports arguments -fvisibility=hidden: YES
            Found pkg-config: YES (/usr/bin/pkg-config) 2.3.0
            Found CMake: /usr/bin/cmake (3.28.3)
            Run-time dependency cairo found: NO (tried pkgconfig and cmake)
      
            ../cairo/meson.build:31:12: ERROR: Dependency "cairo" not found, tried pkgconfig and cmake
      
            A full log can be found at /tmp/pip-install-tw8dj5cn/pycairo_03c0def5edfc40ee9d4235b213c4a82f/.mesonpy-243nssi0/meson-logs/meson-log.txt
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by BruceWayne-Linux** [comment]
Just ran the things you said in the above comments on arch linux. No errors whatsoever. Python backend seems to be the issue. With it disabled, even on arch, the colors are loading wrongly like on fedora.

**Comment by FrancescoCaracciolo** [comment]
Ti fix the python issue above try removing pygoobject from requirements.txt and run it again, maybe il will work

**Comment by BruceWayne-Linux** [comment]
Mmm. Not sure what made it work but i tried installing materialyoucolor manually, since when i ran local-install.sh it kept showing errors. so installed python3-devel package from fedora repository and then it got installed. (Without python3-devel on fedora, materialyoucolor won't install; it gives a g++ error). then removed pygobject from the requirements.txt.
It's working now.

**Comment by chrostino** [comment]
getting kinda the same error here.
I installed python3-devel package in advance and in fact colors seem to apply correctly, but there are still some issues:
- I get [this](https://github.com/FrancescoCaracciolo/material-you-colors/issues/8#issuecomment-2449724117) same issue
- no shell theme is installed from the extension, so I can't change it in gnome tweaks
- a lot of gtk apps that I think should get themed don't or get themed incorrectly, it might be related to the gnome shell issue?
- also changing the color profile in the extension settings either does nothing or breaks the whole theme, reverting to normal gtk colors

**Comment by BruceWayne-Linux** [comment]
@chrostino 1st and 2nd issue can be fixed by installing sass through npm.
after installing sass, make sure you create 'themes' folder in /.local/share/
this fixed the issue of shell theming for me.

**Comment by chrostino** [comment]
yes I was missing the `~/.local/share/themes` folder, I had the `~/.themes` folder instead, but once i removed that and created `~/.local/share/themes` the extension stopped working entirely. I even tried uninstalling and reinstalling

**Comment by BruceWayne-Linux** [comment]
damn, well maybe clear pywal's cached colorschemes too.
also is this package installed 'python3-gobject'? maybe works then?

**Comment by BruceWayne-Linux** [comment]
i recently did a new install of fedora, i did the things mentioned in this issue, the extension works like it should.

**Comment by chrostino** [comment]
`python3-gobject` is also installed, but I don't think it's a dependencies issue since aside form the shell theme missing the extension was working almost fine before. I really don't know what caused it to stop working, the only things that I changed were creating the `~/.themes` folder, then deleting it and creating `~/.local/share/themes`. I also tried reinstalling the extension completely (first removing it through extension manager, then going into `~/.local/share/gnome-shell/` and removing the folder of the extension, then reinstalling following the guide) but didn't work

**Comment by BruceWayne-Linux** [comment]
hmm. seems odd.
what about pywal cache? if you also cleared it and still not working, then run `./run_integration.sh` from `~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-materialu`
should give an idea if any error is there.

**Comment by chrostino** [comment]
only cache I tried to clean was the one in `~/.npm`, is pywal cache found in `~/.local/lib/python3.13/site-packages/pywal/__pycache__/` or just `~/.cache/wal/` (or both)?
anyway from `./run_integration.sh` I get this
```
Traceback (most recent call last):
  File "/home/brudda/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-material-you/extension_integration.py", line 7, in <module>
    from material_color_utilities_python.utils.theme_utils import *
  File "/home/brudda/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-material-you/material_color_utilities_python/__init__.py", line 1, in <module>
    from .utils.image_utils import *
  File "/home/brudda/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-material-you/material_color_utilities_python/utils/image_utils.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

```
I am missing the numpy module, so should I install all requirements through `./install.sh` or just numpy with pip; I am asking since I saw that you had to remove `pygobject` from `requirements.text` so I was wandering if I also needed to in order to avoid conflicts or if it's best to install all

**Comment by BruceWayne-Linux** [comment]
only clearing `/.cache/wal/` is fine.
yes, run `./local-install.sh` . infact running `./local-install.sh` is what makes it work properly on fedora i guess.
and yea, remove `pygobject` from `requirements.txt`(installing pygobject through pip is giving error, so installed `python3-gobject` through `dnf`)

**Comment by chrostino** [comment]
ok it kinda worked, at least the extension now does something and colors stuff (also the shell theme appeared), but I still get major coloring issues, mainly in the shell and also in various app, even though I set the shell theme to MaterialYou in gnome tweaks
`./run_integration.sh` now gives me
```
Could not load schemas from /root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas: Failed to open file “/root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas/gschemas.compiled”: open() failed: No such file or directory
Command '['bash', '-c', 'gsettings --schemadir ~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas get org.gnome.shell.extensions.material-you-colors scheme']' returned non-zero exit status 1.
Could not load schemas from /root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas: Failed to open file “/root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas/gschemas.compiled”: open() failed: No such file or directory
Command '['bash', '-c', 'gsettings --schemadir ~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas get org.gnome.shell.extensions.material-you-colors enable-accent-colors']' returned non-zero exit status 1.
Could not load schemas from /root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas: Failed to open file “/root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas/gschemas.compiled”: open() failed: No such file or directory
Command '['bash', '-c', 'gsettings --schemadir ~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas get org.gnome.shell.extensions.material-you-colors accent-color']' returned non-zero exit status 1.
Could not load schemas from /root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas: Failed to open file “/root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas/gschemas.compiled”: open() failed: No such file or directory
Command '['bash', '-c', 'gsettings --schemadir ~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas get org.gnome.shell.extensions.material-you-colors show-notifications']' returned non-zero exit status 1.
Could not load schemas from /root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas: Failed to open file “/root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas/gschemas.compiled”: open() failed: No such file or directory
Command '['bash', '-c', 'gsettings --schemadir ~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas get org.gnome.shell.extensions.material-you-colors extra-command']' returned non-zero exit status 1.
Could not load schemas from /root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas: Failed to open file “/root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas/gschemas.compiled”: open() failed: No such file or directory
Command '['bash', '-c', 'gsettings --schemadir ~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas get org.gnome.shell.extensions.material-you-colors resize-height']' returned non-zero exit status 1.
Could not load schemas from /root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas: Failed to open file “/root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas/gschemas.compiled”: open() failed: No such file or directory
Command '['bash', '-c', 'gsettings --schemadir ~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas get org.gnome.shell.extensions.material-you-colors resize-width']' returned non-zero exit status 1.
Could not load schemas from /root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas: Failed to open file “/root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas/gschemas.compiled”: open() failed: No such file or directory
Command '['bash', '-c', 'gsettings --schemadir ~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas get org.gnome.shell.extensions.material-you-colors enable-pywal-theming']' returned non-zero exit status 1.
Could not load schemas from /root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas: Failed to open file “/root/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas/gschemas.compiled”: open() failed: No such file or directory
Command '['bash', '-c', 'gsettings --schemadir ~/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/schemas get org.gnome.shell.extensions.material-you-colors arcmenu-theming']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/brudda/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-material-you/extension_integration.py", line 244, in <module>
    apply_theme(accent_color_applied)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brudda/.local/share/gnome-shell/extensions/material-you-colors@francescocaracciolo.github.io/adwaita-material-you/extension_integration.py", line 207, in apply_theme
    theme = theme_from_image_2(Image.open(wall_path), int(width), int(height), is_dark)
                                                      ~~~^^^^^^^
ValueError: invalid literal for int() with base 10: ''

```

I'll leave some example screenshots here

shell examples
![Image](https://github.com/user-attachments/assets/25a7cc65-56c9-467a-9d56-92540e1242cd)

![Image](https://github.com/user-attachments/assets/8f4c4dc0-2a03-4c42-a502-503b3cb9999e)

blackbox terminal
![Image](https://github.com/user-attachments/assets/6643b878-e1aa-4c28-9ef2-b40283cb6e34)

 text editor (gnome default), this might not be an extension issue tho
![Image](https://github.com/user-attachments/assets/343299e9-c351-4807-b4a5-f0ee4fd9bb45)

xournal++
![Image](https://github.com/user-attachments/assets/fb8d42a9-d0d6-4d20-aced-d2149edb6ed8)

and there are more apps displaying similar behaviours, more specifically some gtk4 apps have parts that don't get colored like the text editor exaple, while a lot of gtk3 apps don't get colored at all like xournal++. I believe it's llnked to the shell not getting themed but I'm not sure

**Comment by BruceWayne-Linux** [comment]
for gtk3 apps use this theme `adw-gtk3-theme`. you can install it through `dnf`.
try changing wallpaper, then log out and log in. see if the color changes. if still same, then try setting colorscheme by `wal` manually from terminal.

also, did you put this in ~/.bashrc or ~/.zshrc ?
```
if [[ -f "$HOME/.cache/wal/sequences" ]]; then
    (cat $HOME/.cache/wal/sequences)
fi
```

**Comment by chrostino** [comment]
installed `adw-gtk3-theme` and changed wallpaper but even though I logged out and logged back in the extension decided to just ignore the new blue wallpaper and stay on red, nothing changed, Also yes I did put that part in my `.zshrc`, in fact the font in my terminal is the only thing that changed color when changing wallpaper

**Comment by BruceWayne-Linux** [comment]
#

>in fact the font in my terminal is the only thing that changed color when changing wallpaper

looks like `pywal` is working then.
using python backend in the extension?

**Comment by chrostino** [comment]
yep, also toggled the "enable backend faster"

**Comment by BruceWayne-Linux** [comment]
try manually setting the wallpaper color scheme through pywal.
`wal -i "/path/to/img.jpg"`
see if any change in terminal color scheme and see if you get a notification from the extension.

**Comment by BruceWayne-Linux** [comment]
automatic colorscheme does not work for me either with change in wallpaper. i apply through `wal -i "/path/to/img.jpg"`.

**Comment by chrostino** [comment]
damn that's a bummer, but I can live with that, the only thing thats bugging me out is this issue with applying colors to the shell and other stuff
anyway `wal -i "/path/to/img.jpg"` didn't seem to do much to the colors although it triggered the notification. Disabliung pywal theming in extension settings and changing the color manually seems to be much more reliable, but the issues listed above still remain

**Comment by BruceWayne-Linux** [comment]
hmm. still not sure why its acting weird for you. maybe on other systems too.
hoping a fix arrives soon or with next release which fixes stuff and works default on fedora.

**Comment by chrostino** [comment]
just to get back at this I was able to fix the issue that didn't theme all of my apps, I am not sure why but reinstalling the adw-gtk3 theme and reapplying it was enough. The only issues left are the shell not theming and the accent color not changing automatically through pywal, but this is already a big improvement
Also I would suggest rewriting the installation instructions in a more legible way and with a note for fedora users about the pygobject issue
